### GENERAL SETTINGS ###

# Site settings
title: disconomics
description: "Weekly shows &nbsp;&nbsp; | &nbsp;&nbsp; Daily grouillades"

analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://disconomics.xyz"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#ffffff" 
  primary_rgb: "118,42,131" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#231f20"
  link: "#1b7837"
  link_hover: "#762a83"
  footer_heading: "#ffffff"
  footer_content: "#ffffff"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: email
    url: disconomics@gmail
  - title: twitter
    url: https://twitter.com/_disconomics
  - title: facebook
    url: https://www.facebook.com/disconomics
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
email: disconomics@gmail.com


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Phil
    social:
      - title: twitter
        url: https://twitter.com/phil_huot
  - name: Matt
    social:
      - title: twitter
        url: https://twitter.com/Matt_Caron
  - name: Étienne
    social:
      - title: twitter
        url:  https://twitter.com/etpinard
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Grouillades!"
